const fs = require('fs');
const path = require('path');

const rootDir = __dirname;
const frontendDir = path.join(rootDir, 'frontend');

if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
}

console.log('🚀 Creazione dei file HTML mancanti...');

// ============================================================
// 1. ARTICOLIUNIFICATO.HTML
// ============================================================
const articoliHtml = [
    '<!DOCTYPE html>',
    '<html lang="it">',
    '<head>',
    '  <link rel="icon" type="image/png" href="/images/kastle-logo.png">',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>📦 Gestione Articoli</title>',
    '  <style>',
    '    * { box-sizing: border-box; margin: 0; padding: 0; }',
    '    body { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 0; height: 100vh; overflow: hidden; }',
    '    .compact-bar { display: flex; justify-content: space-between; align-items: center; background: white; border-radius: 0 0 12px 12px; padding: 4px 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }',
    '    .btn-secondary { background: #6c757d; border: none; padding: 2px 8px; font-size: 0.7rem; border-radius: 4px; cursor: pointer; color: white; }',
    '    .container { flex: 1; display: flex; flex-direction: column; max-width: 1600px; width: 100%; margin: 0 auto; background: white; border-radius: 16px 16px 0 0; box-shadow: 0 8px 20px rgba(0,0,0,0.05); padding: 2px 20px 20px 20px; height: calc(100vh - 50px); overflow: hidden; }',
    '    h2 { margin: 5px 0 8px 0; font-size: 1.3rem; border-left: 5px solid #1a73e8; padding-left: 12px; color: #1e2a3a; display: inline-block; }',
    '    .form-row-5col, .form-row-3col, .form-row-4col-slim, .form-row-2col { display: grid; gap: 8px; margin-bottom: 6px; }',
    '    .form-row-5col { grid-template-columns: repeat(5, 1fr); }',
    '    .form-row-3col { grid-template-columns: 2fr 1fr 1fr; }',
    '    .form-row-4col-slim { grid-template-columns: 1fr 1fr auto auto; }',
    '    .form-row-2col { grid-template-columns: 2fr 1fr 1fr; }',
    '    .form-group { margin-bottom: 0; }',
    '    label { font-weight: 600; font-size: 0.7rem; margin-bottom: 2px; display: block; color: #2c3e50; }',
    '    input, select, textarea { width: 100%; padding: 4px 6px; border: 1px solid #cbd5e0; border-radius: 6px; font-size: 0.75rem; background: #f9fafb; }',
    '    .btn { background: linear-gradient(135deg, #1a73e8, #0f5bb5); color: white; border: none; padding: 4px 10px; border-radius: 6px; cursor: pointer; font-size: 0.75rem; transition: 0.1s; }',
    '    .btn:hover { transform: translateY(-1px); box-shadow: 0 2px 6px rgba(0,0,0,0.1); }',
    '    .btn-danger { background: linear-gradient(135deg, #dc3545, #b02a37); }',
    '    .btn-warning { background: #f39c12; color: white; }',
    '    .btn-success { background: #27ae60; }',
    '    .btn-secondary { background: linear-gradient(135deg, #6c757d, #565e64); }',
    '    .table-wrapper { overflow-x: auto; overflow-y: auto; flex: 1; min-height: 0; margin-top: 10px; border-radius: 10px; border: 1px solid #e2e8f0; background: white; }',
    '    table { width: 100%; min-width: 1300px; border-collapse: collapse; font-size: 0.7rem; }',
    '    th, td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; text-align: left; }',
    '    th { background: #f1f5f9; font-weight: 600; position: sticky; top: 0; z-index: 10; cursor: pointer; }',
    '    tr:hover td { background: #f8fafc; }',
    '    .action-buttons { display: flex; gap: 4px; justify-content: center; }',
    '    .message { padding: 6px 10px; margin-bottom: 8px; border-radius: 8px; font-size: 0.75rem; }',
    '    .success { background: #d1fae5; color: #065f46; border-left: 4px solid #10b981; }',
    '    .error { background: #fee2e2; color: #991b1b; border-left: 4px solid #ef4444; }',
    '    .spinner { display: inline-block; width: 12px; height: 12px; border: 2px solid #e2e8f0; border-top-color: #1a73e8; border-radius: 50%; animation: spin 0.6s linear infinite; }',
    '    @keyframes spin { to { transform: rotate(360deg); } }',
    '    .assignment-group { background: #f8f9fa; padding: 6px 10px; border-radius: 10px; margin: 6px 0; }',
    '    .inline-checkbox { display: flex; align-items: center; gap: 6px; margin-top: 18px; }',
    '    .inline-checkbox input { width: auto; }',
    '    .modal { display: none; position: fixed; top:0; left:0; width:100%; height:100%; background: rgba(0,0,0,0.5); justify-content: center; align-items: center; z-index: 1000; }',
    '    .modal-content { background: white; border-radius: 20px; width: 90%; max-width: 700px; max-height: 85vh; overflow-y: auto; padding: 20px; }',
    '    .modal-buttons { display: flex; justify-content: flex-end; gap: 10px; margin-top: 15px; }',
    '    .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 10px; }',
    '    .sigle-table { width: 100%; margin-top: 10px; border-collapse: collapse; }',
    '    .sigle-table th, .sigle-table td { padding: 5px; border: 1px solid #ddd; }',
    '    .header-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }',
    '    .logo img { height: 28px; }',
    '    .required-error { border: 1px solid #ef4444 !important; background-color: #fee2e2 !important; }',
    '    #modalSigle .modal-content { max-width: 1200px; width: 95%; }',
    '    .sigle-table { overflow-x: auto; display: block; }',
    '    .sigle-table th, .sigle-table td { white-space: nowrap; padding: 8px 12px; }',
    '    .sigle-table input[type="number"] { width: 80px; }',
    '  </style>',
    '</head>',
    '<body>',
    '<div class="compact-bar">',
    '  <div class="logo"><img src="/images/kastle-logo.png" alt="Kastle"></div>',
    '  <div style="display: flex; gap: 6px;">',
    '    <button class="btn-secondary" onclick="window.location.href=\'MenuPrincipale.html\'">🏠 Menu</button>',
    '    <button class="btn-secondary" onclick="logout()">🚪 Logout</button>',
    '  </div>',
    '</div>',
    '<div class="container">',
    '  <div class="header-bar"><h2>📦 Gestione Articoli</h2></div>',
    '  <div id="messageArea"></div>',
    '  <form id="articleForm" onsubmit="return false;">',
    '    <div class="form-row-5col">',
    '      <div class="form-group"><label>Magazzino *</label><select id="magazzino" required></select></div>',
    '      <div class="form-group"><label>Settore *</label><select id="settore" required></select></div>',
    '      <div class="form-group"><label>Categoria *</label><select id="categoria" required></select></div>',
    '      <div class="form-group"><label>Marca *</label><select id="marca" required></select></div>',
    '      <div class="form-group"><div class="inline-checkbox"><input type="checkbox" id="assegnaCheckbox"><label for="assegnaCheckbox">📤 Assegna</label></div></div>',
    '    </div>',
    '    <div class="form-row-3col">',
    '      <div class="form-group"><label>Descrizione *</label><input type="text" id="descrizione" list="descrizioneList" required autocomplete="off"><datalist id="descrizioneList"></datalist></div>',
    '      <div class="form-group"><label>Codice Modello</label><input type="text" id="codice_modello" list="codice_modelloList" autocomplete="off"><datalist id="codice_modelloList"></datalist></div>',
    '      <div class="form-group"><label>Lunghezza (cm)</label><input type="text" id="lunghezza" list="lunghezzaList" autocomplete="off"><datalist id="lunghezzaList"></datalist></div>',
    '    </div>',
    '    <div class="form-row-4col-slim">',
    '      <div class="form-group"><label>Durezza</label><input type="text" id="durezza" list="durezzaList" autocomplete="off"><datalist id="durezzaList"></datalist></div>',
    '      <div class="form-group"><label>Quantità *</label><input type="number" id="quantita" value="1" min="1" step="1" required></div>',
    '      <div class="form-group"><label>Versione</label><input type="text" id="versione" value="1.0"></div>',
    '      <div class="form-group"><label>Note</label><textarea id="note" rows="1"></textarea></div>',
    '    </div>',
    '    <div class="form-group" id="siglaContainer" style="display: none;"><label>Sigla *</label><select id="siglaSelect" required></select><button type="button" class="btn btn-sm btn-secondary" onclick="apriModalNuovaSigla()">➕ Nuova</button></div>',
    '    <div class="form-row-2col"><div class="form-group"><button type="button" class="btn" id="saveBtn" onclick="salvaArticolo()">💾 Salva</button></div><div class="form-group"><button type="button" class="btn btn-secondary" onclick="resetFiltri()">🔄 Reset</button></div></div>',
    '    <div id="assegnaSection" style="display:none;" class="assignment-group"><div class="form-row-2col"><div class="form-group"><label>Destinazione</label><select id="destinazioneTipo"><option value="PROMOTER">Promoter</option><option value="NEGOZIO">Negozio</option><option value="CLIENTE">Cliente</option><option value="AGENTE">Agente</option></select></div><div class="form-group"><label>Seleziona destinazione *</label><select id="destinazioneId"></select></div></div><div class="form-group"><label>Note assegnazione</label><input type="text" id="assegnaNote"></div></div>',
    '  </form>',
    '  <div class="table-wrapper"><table id="tabellaArticoli"><thead><th data-sort="codice">Codice</th><th data-sort="id">ID</th><th data-sort="descrizione">Descrizione</th><th data-sort="descrizione_completa">Descrizione Completa</th><th data-sort="magazzino_nome">Magazzino</th><th data-sort="categoria_nome">Categoria</th><th data-sort="marca_nome">Marca</th><th data-sort="lunghezza">Lunghezza</th><th data-sort="durezza">Durezza</th><th data-sort="quantita_totale">Qtà Tot</th><th data-sort="giacenza">Giacenza</th><th data-sort="quantita_obsoleta">Qtà Obs</th><th data-sort="stato">Stato</th><th>Sigle</th><th>Azioni</th></thead><tbody></tbody></table></div>',
    '</div>',
    '<!-- Modal Modifica Articolo --><div id="modalEdit" class="modal"><div class="modal-content"><h3>✏️ Modifica Articolo</h3><form id="editForm" onsubmit="return false;"><input type="hidden" id="editId"><div class="form-row"><div class="form-group"><label>Magazzino *</label><select id="editMagazzino" required></select></div><div class="form-group"><label>Settore *</label><select id="editSettore" required></select></div><div class="form-group"><label>Categoria *</label><select id="editCategoria" required></select></div><div class="form-group"><label>Marca *</label><select id="editMarca" required></select></div></div><div class="form-group"><label>Descrizione *</label><input type="text" id="editDescrizione" list="editDescrizioneList" required><datalist id="editDescrizioneList"></datalist></div><div class="form-row"><div class="form-group"><label>Codice Modello</label><input type="text" id="editCodiceModello" list="editModelloList"><datalist id="editModelloList"></datalist></div><div class="form-group"><label>Lunghezza (cm)</label><input type="text" id="editLunghezza" list="editLunghezzaList"><datalist id="editLunghezzaList"></datalist></div></div><div class="form-row"><div class="form-group"><label>Durezza</label><input type="text" id="editDurezza" list="editDurezzaList"><datalist id="editDurezzaList"></datalist></div><div class="form-group"><label>Quantità Totale *</label><input type="number" id="editQuantita" required min="0"></div></div><div class="form-group"><label>Note</label><textarea id="editNote" rows="2"></textarea></div><div class="modal-buttons"><button type="button" class="btn" onclick="salvaModifica()">💾 Salva</button><button type="button" class="btn btn-danger" onclick="chiudiModale()">Annulla</button></div></form></div></div>',
    '<!-- Modal Sigle --><div id="modalSigle" class="modal"><div class="modal-content"><h3>🔖 Gestione Sigle</h3><p><strong>Articolo:</strong> <span id="sigleArticoloDesc"></span></p><table class="sigle-table"><thead><tr><th>Sigla</th><th>Durezza</th><th>Codice Modello</th><th>Note</th><th>Quantità</th><th>Azioni</th></tr></thead><tbody id="sigleTableBody"></tbody></table><div class="form-row"><div class="form-group"><label>Nuova Sigla</label><input type="text" id="nuovaSigla" placeholder="Sigla"></div><div class="form-group"><label>Durezza</label><input type="text" id="nuovaSiglaDurezza"></div><div class="form-group"><label>Codice Modello</label><input type="text" id="nuovaSiglaModello" list="modelliList"><datalist id="modelliList"></datalist></div><div class="form-group"><label>Note</label><input type="text" id="nuovaSiglaNote"></div><div class="form-group"><button class="btn" onclick="aggiungiSigla()">➕ Aggiungi</button></div></div><div class="modal-buttons"><button class="btn btn-secondary" onclick="chiudiModalSigle()">Chiudi</button></div></div></div>',
    '<!-- Modal Obsolescenza --><div id="modalObsoleto" class="modal"><div class="modal-content" style="max-width:400px;"><h3>📦 Rendi Obsoleto</h3><p>Articolo: <span id="obsArticoloDesc"></span></p><div class="form-group"><label>Quantità da rendere obsoleta *</label><input type="number" id="obsQuantita" min="1" class="form-control"><small>Disponibile: <span id="obsDisponibile"></span></small></div><div class="form-group"><label>Note</label><input type="text" id="obsNote" class="form-control"></div><div class="modal-buttons"><button class="btn btn-warning" onclick="confermaObsolescenza()">Conferma</button><button class="btn btn-secondary" onclick="chiudiModalObsoleto()">Annulla</button></div></div></div>',
    '<!-- Modal Vendita --><div id="modalVendita" class="modal"><div class="modal-content" style="max-width:500px;"><h3>💰 Registra Vendita</h3><p>Oggetto: <span id="venditaOggettoDesc"></span></p><div class="form-group"><label>Tipo Soggetto *</label><select id="venditaTipoSoggetto" class="form-control" onchange="caricaSoggettiPerTipoVendita(this.value)"><option value="">Seleziona tipo...</option><option value="PROMOTER">Promoter</option><option value="NEGOZIO">Negozio</option><option value="CLIENTE">Cliente</option><option value="AGENTE">Agente</option></select></div><div class="form-group"><label>Soggetto *</label><select id="venditaSoggettoId" class="form-control" disabled><option value="">Seleziona prima il tipo</option></select><button type="button" class="btn btn-secondary btn-sm" onclick="apriNuovoSoggetto()" style="margin-top:5px;">➕ Nuovo Soggetto</button></div><div class="form-group" id="venditaSiglaGroup" style="display: none;"><label>Sigla *</label><select id="venditaSiglaId" class="form-control"><option value="">Qualsiasi sigla</option></select></div><div class="form-group"><label>Quantità da vendere *</label><input type="number" id="venditaQuantita" min="1" class="form-control"><small>Disponibile: <span id="venditaDisponibile"></span></small></div><div class="form-group"><label>Importo (€)</label><input type="number" id="venditaImporto" step="0.01" class="form-control"></div><div class="form-group"><label>Note</label><input type="text" id="venditaNote" class="form-control"></div><div class="modal-buttons"><button class="btn btn-success" onclick="confermaVendita()">Vendi</button><button class="btn btn-secondary" onclick="chiudiModalVendita()">Annulla</button></div></div></div>',
    '<script>',
    'function getAuthHeader() { const token = localStorage.getItem("token"); return token ? { "Authorization": "Bearer " + token } : {}; }',
    'function showMessage(msg, type) { const div = document.getElementById("messageArea"); div.innerHTML = `<div class="message ${type}">${msg}</div>`; setTimeout(() => div.innerHTML = "", 5000); }',
    'async function apiFetch(endpoint, options = {}) { const headers = { "Content-Type": "application/json", ...getAuthHeader(), ...options.headers }; const res = await fetch("/api" + endpoint, { ...options, headers }); if (!res.ok) { let err = `Errore ${res.status}`; try { const data = await res.json(); err = data.message || err; } catch(e) {} throw new Error(err); } return res.json(); }',
    'function restoreSession() { return !!localStorage.getItem("token"); }',
    'function logout() { localStorage.removeItem("token"); localStorage.removeItem("user"); window.location.href = "Login.html"; }',
    'let magazzini = [], settori = [], categorie = [], marche = []; let articoliCorrente = []; let sortColumn = "codice", sortAsc = true; let currentObsId = null, currentVenditaId = null, currentVenditaTipo = null, currentVenditaSigle = []; let currentSigleArticoloId = null;',
    'const magazzinoSelect = document.getElementById("magazzino"); const settoreSelect = document.getElementById("settore"); const categoriaSelect = document.getElementById("categoria"); const marcaSelect = document.getElementById("marca"); const descrizioneInput = document.getElementById("descrizione"); const codiceModelloInput = document.getElementById("codice_modello"); const lunghezzaInput = document.getElementById("lunghezza"); const durezzaInput = document.getElementById("durezza"); const quantitaInput = document.getElementById("quantita");',
    'async function caricaSoggettiPerTipoVendita(tipo) { const selectSoggetto = document.getElementById("venditaSoggettoId"); if (!selectSoggetto) return; if (!tipo) { selectSoggetto.innerHTML = "<option value=\"\">Seleziona prima il tipo</option>"; selectSoggetto.disabled = true; return; } selectSoggetto.innerHTML = "<option value=\"\">Caricamento...</option>"; selectSoggetto.disabled = true; try { const data = await apiFetch(`/soggetti/tipo/${tipo}`); selectSoggetto.innerHTML = "<option value=\"\">Seleziona soggetto...</option>"; if (Array.isArray(data) && data.length) { data.forEach(item => { let testo = tipo === "PROMOTER" ? `${item.nome} ${item.cognome || ""}`.trim() : item.nome; selectSoggetto.appendChild(new Option(testo, item.id)); }); } else { selectSoggetto.innerHTML = "<option value=\"\">Nessun soggetto trovato</option>"; } selectSoggetto.disabled = false; } catch (err) { selectSoggetto.innerHTML = "<option value=\"\">Errore nel caricamento</option>"; selectSoggetto.disabled = true; } }',
    'async function apriModaleVendita(id, descrizione, tipoOggetto, disponibile) { currentVenditaId = id; currentVenditaTipo = tipoOggetto; document.getElementById("venditaOggettoDesc").innerText = descrizione; document.getElementById("venditaDisponibile").innerText = disponibile; const qtyInput = document.getElementById("venditaQuantita"); qtyInput.max = disponibile; qtyInput.value = disponibile > 0 ? 1 : 0; document.getElementById("venditaImporto").value = ""; document.getElementById("venditaNote").value = ""; const tipoSelect = document.getElementById("venditaTipoSoggetto"); const soggettoSelect = document.getElementById("venditaSoggettoId"); tipoSelect.value = ""; soggettoSelect.innerHTML = "<option value=\"\">Seleziona prima il tipo</option>"; soggettoSelect.disabled = true; const siglaGroup = document.getElementById("venditaSiglaGroup"); const siglaSelect = document.getElementById("venditaSiglaId"); if (tipoOggetto === "ARTICOLO") { try { const sigle = await apiFetch(`/articoli/${id}/sigle`); currentVenditaSigle = sigle.filter(s => s.quantita > 0); siglaSelect.innerHTML = "<option value=\"\">Qualsiasi sigla</option>"; for (const s of currentVenditaSigle) { const option = document.createElement("option"); option.value = s.id; option.textContent = `${s.sigla} (disponibile: ${s.quantita})`; siglaSelect.appendChild(option); } siglaGroup.style.display = "block"; } catch (err) { console.error(err); siglaGroup.style.display = "none"; } } else { siglaGroup.style.display = "none"; } document.getElementById("modalVendita").style.display = "flex"; }',
    'function chiudiModalVendita() { document.getElementById("modalVendita").style.display = "none"; currentVenditaId = null; currentVenditaSigle = []; }',
    'async function confermaVendita() { const clienteId = document.getElementById("venditaSoggettoId").value; const quantita = parseInt(document.getElementById("venditaQuantita").value); const importo = document.getElementById("venditaImporto").value; const note = document.getElementById("venditaNote").value.trim(); const siglaId = document.getElementById("venditaSiglaId").value; if (!clienteId) { showMessage("Seleziona un soggetto", "error"); return; } if (isNaN(quantita) || quantita <= 0) { showMessage("Quantità non valida", "error"); return; } if (currentVenditaTipo === "ARTICOLO" && siglaId) { const sigla = currentVenditaSigle.find(s => s.id == siglaId); if (!sigla || sigla.quantita < quantita) { showMessage(`La sigla selezionata ha solo ${sigla ? sigla.quantita : 0} pezzi disponibili`, "error"); return; } } const oggetti = [{ tipoOggetto: currentVenditaTipo, oggettoId: currentVenditaId, quantita, siglaId: siglaId || null }]; try { const res = await apiFetch("/vendite", { method: "POST", body: JSON.stringify({ oggetti, clienteId, importo: importo || null, note }) }); if (res.success) { showMessage(res.message, "success"); chiudiModalVendita(); refreshTabella(); } else { showMessage(res.message, "error"); } } catch (err) { showMessage(err.message, "error"); } }',
    'function apriNuovoSoggetto() { window.open("GestioneSoggetti.html", "_blank"); }',
    'async function caricaAnagrafiche() { try { [magazzini, settori, categorie, marche] = await Promise.all([ apiFetch("/anagrafiche/magazzini"), apiFetch("/anagrafiche/settori"), apiFetch("/anagrafiche/categorie"), apiFetch("/anagrafiche/marche") ]); function popola(sel, items, valKey, textKey) { sel.innerHTML = "<option value=\"\">Seleziona</option>"; items.forEach(i => sel.appendChild(new Option(i[textKey], i[valKey]))); } popola(magazzinoSelect, magazzini, "id", "nome"); popola(settoreSelect, settori, "id", "nome"); popola(categoriaSelect, categorie, "id", "nome"); popola(marcaSelect, marche, "id", "nome"); } catch(err) { showMessage("Errore caricamento anagrafiche", "error"); } }',
    'const filterFields = ["magazzino","settore","categoria","marca","descrizione","lunghezza","durezza","codice_modello"]; const endpointMap = { descrizione: "/articoli/valori/descrizioni", lunghezza: "/articoli/valori/lunghezze", durezza: "/articoli/valori/durezze", codice_modello: "/articoli/valori/modelli" };',
    'function getCurrentFilters() { const f = {}; for (let field of filterFields) { let el = document.getElementById(field); if (field === "magazzino") el = magazzinoSelect; else if (field === "settore") el = settoreSelect; else if (field === "categoria") el = categoriaSelect; else if (field === "marca") el = marcaSelect; if (el) f[field] = el.value; } return f; }',
    'async function aggiornaDatalist(campo, endpoint) { const filters = getCurrentFilters(); delete filters[campo]; const params = new URLSearchParams(); for (let [k,v] of Object.entries(filters)) if (v) params.append(k,v); const url = `${endpoint}?${params.toString()}`; try { const data = await apiFetch(url); const datalist = document.getElementById(`${campo}List`); if (datalist) { datalist.innerHTML = ""; data.forEach(item => { const opt = document.createElement("option"); opt.value = item[campo]; datalist.appendChild(opt); }); } } catch(err) { console.error(err); } }',
    'async function refreshAllDatalists() { for (let [campo, ep] of Object.entries(endpointMap)) await aggiornaDatalist(campo, ep); }',
    'let refreshDebounce; function refreshTabella() { caricaArticoli(); } function refreshTabellaDebounced() { clearTimeout(refreshDebounce); refreshDebounce = setTimeout(refreshTabella, 300); }',
    'function attachFormEvents() { const selects = [magazzinoSelect, settoreSelect, categoriaSelect, marcaSelect]; selects.forEach(s => s.addEventListener("change", () => { refreshAllDatalists(); refreshTabellaDebounced(); })); const inputs = ["descrizione", "lunghezza", "durezza", "codice_modello"]; inputs.forEach(id => { const el = document.getElementById(id); if (el) el.addEventListener("input", () => { refreshAllDatalists(); refreshTabellaDebounced(); }); }); }',
    'async function caricaArticoli() { try { const params = new URLSearchParams(); if (magazzinoSelect.value) params.append("magazzino", magazzinoSelect.value); if (settoreSelect.value) params.append("settore", settoreSelect.value); if (categoriaSelect.value) params.append("categoria", categoriaSelect.value); if (marcaSelect.value) params.append("marca", marcaSelect.value); if (descrizioneInput.value) params.append("descrizione", descrizioneInput.value); if (codiceModelloInput.value) params.append("codice_modello", codiceModelloInput.value); if (lunghezzaInput.value) params.append("lunghezza", lunghezzaInput.value); if (durezzaInput.value) params.append("durezza", durezzaInput.value); const res = await apiFetch(`/articoli?${params.toString()}`); if (res.success) { articoliCorrente = res.data; renderTabella(); } else showMessage(res.message, "error"); } catch(err) { showMessage(err.message, "error"); } }',
    'function compare(a,b,col) { let va = a[col], vb = b[col]; if (col === "quantita_totale" || col === "giacenza" || col === "quantita_obsoleta") { va = Number(va)||0; vb = Number(vb)||0; } else if (col === "lunghezza") { va = parseFloat(va)||0; vb = parseFloat(vb)||0; } else { va = (va||"").toString().toLowerCase(); vb = (vb||"").toString().toLowerCase(); } if (va < vb) return -1; if (va > vb) return 1; return 0; }',
    'function ordinaArticoli() { articoliCorrente.sort((a,b) => { let r = compare(a,b,sortColumn); if (!sortAsc) r = -r; if (r===0 && sortColumn!=="codice") r = compare(a,b,"codice"); return r; }); }',
    'function aggiornaIndicatoriOrdine() { document.querySelectorAll("#tabellaArticoli th").forEach(th => { const col = th.getAttribute("data-sort"); if (col === sortColumn) th.innerText = th.innerText.replace(/[↑↓]/g, "") + (sortAsc ? " ↑" : " ↓"); else th.innerText = th.innerText.replace(/[↑↓]/g, ""); }); }',
    'function renderTabella() { ordinaArticoli(); const tbody = document.querySelector("#tabellaArticoli tbody"); tbody.innerHTML = ""; if (!articoliCorrente.length) { tbody.innerHTML = "<tr><td colspan=\"15\">Nessun articolo</td></tr>"; return; } articoliCorrente.forEach(a => { const mag = magazzini.find(m => m.id == a.magazzino)?.nome || a.magazzino; const cat = categorie.find(c => c.id == a.categoria)?.nome || a.categoria; const mar = marche.find(m => m.id == a.marca)?.nome || a.marca; const giac = a.GIACENZA_REALE; const row = tbody.insertRow(); row.insertCell(0).innerText = a.codice || "-"; row.insertCell(1).innerText = a.articolo_id; row.insertCell(2).innerText = a.descrizione; row.insertCell(3).innerText = a.descrizione_completa; row.insertCell(4).innerText = mag; row.insertCell(5).innerText = cat; row.insertCell(6).innerText = mar; row.insertCell(7).innerText = a.lunghezza || ""; row.insertCell(8).innerText = a.durezza || ""; row.insertCell(9).innerText = a.quantita_totale; row.insertCell(10).innerText = giac; row.insertCell(11).innerText = a.quantita_obsoleta || 0; row.insertCell(12).innerText = a.stato || ""; const tdSigle = row.insertCell(13); const btnSigle = document.createElement("button"); btnSigle.textContent = "🔖"; btnSigle.className = "btn"; btnSigle.style.background = "#6c757d"; btnSigle.style.padding = "2px 6px"; btnSigle.onclick = () => apriGestioneSigle(a.articolo_id, a.descrizione); tdSigle.appendChild(btnSigle); const actions = row.insertCell(14); actions.className = "action-buttons"; actions.innerHTML = `<button class="btn" onclick="modificaArticolo(${a.articolo_id})" title="Modifica">✏️</button><button class="btn btn-warning" onclick="apriModaleObsoleto(${a.articolo_id}, '${a.descrizione.replace(/'/g, "\\'")}', ${giac})" title="Obsoleto">📦</button><button class="btn btn-success" onclick="apriModaleVendita(${a.articolo_id}, '${a.descrizione.replace(/'/g, "\\'")}', 'ARTICOLO', ${giac})" title="Vendi">💰</button><button class="btn btn-danger" onclick="eliminaArticolo(${a.articolo_id})" title="Elimina">🗑️</button>`; }); aggiornaIndicatoriOrdine(); }',
    'function handleSort(col) { if (sortColumn === col) sortAsc = !sortAsc; else { sortColumn = col; sortAsc = true; } renderTabella(); }',
    'function attachSortListeners() { document.querySelectorAll("#tabellaArticoli th[data-sort]").forEach(th => { th.addEventListener("click", () => handleSort(th.getAttribute("data-sort"))); }); }',
    'function resetFiltri() { magazzinoSelect.value = ""; settoreSelect.value = ""; categoriaSelect.value = ""; marcaSelect.value = ""; descrizioneInput.value = ""; codiceModelloInput.value = ""; lunghezzaInput.value = ""; durezzaInput.value = ""; refreshAllDatalists(); refreshTabella(); }',
    'function resetErrorStyles() { [magazzinoSelect, settoreSelect, categoriaSelect, marcaSelect, descrizioneInput, quantitaInput].forEach(el => el.classList.remove("required-error")); }',
    'async function salvaArticolo() { resetErrorStyles(); let missing = []; if (!descrizioneInput.value.trim()) missing.push("Descrizione"); if (!magazzinoSelect.value) missing.push("Magazzino"); if (!settoreSelect.value) missing.push("Settore"); if (!categoriaSelect.value) missing.push("Categoria"); if (!marcaSelect.value) missing.push("Marca"); if (!quantitaInput.value || quantitaInput.value <= 0) missing.push("Quantità"); if (missing.length > 0) { showMessage(`Campi obbligatori mancanti: ${missing.join(", ")}`, "error"); if (!descrizioneInput.value.trim()) descrizioneInput.classList.add("required-error"); if (!magazzinoSelect.value) magazzinoSelect.classList.add("required-error"); if (!settoreSelect.value) settoreSelect.classList.add("required-error"); if (!categoriaSelect.value) categoriaSelect.classList.add("required-error"); if (!marcaSelect.value) marcaSelect.classList.add("required-error"); if (!quantitaInput.value || quantitaInput.value <= 0) quantitaInput.classList.add("required-error"); return; } const payload = { descrizione: descrizioneInput.value.trim(), magazzino: parseInt(magazzinoSelect.value), settore: parseInt(settoreSelect.value), categoria: parseInt(categoriaSelect.value), marca: parseInt(marcaSelect.value), lunghezza: lunghezzaInput.value.trim(), durezza: durezzaInput.value.trim(), quantita: parseInt(quantitaInput.value), versione: document.getElementById("versione").value.trim(), note: document.getElementById("note").value.trim(), codiceModello: codiceModelloInput.value.trim() }; const siglaSelect = document.getElementById("siglaSelect"); if (siglaSelect && siglaSelect.value) { payload.siglaId = parseInt(siglaSelect.value); } const saveBtn = document.getElementById("saveBtn"); saveBtn.disabled = true; saveBtn.innerHTML = "<span class=\"spinner\"></span>"; try { const res = await apiFetch("/articoli", { method: "POST", body: JSON.stringify(payload) }); if (res.success) { showMessage(res.message, "success"); if (document.getElementById("assegnaCheckbox").checked) { const assignPayload = { magazzinoId: payload.magazzino, destinazioneTipo: document.getElementById("destinazioneTipo").value, destinazioneId: parseInt(document.getElementById("destinazioneId").value), note: document.getElementById("assegnaNote").value, oggetti: [{ tipoOggetto: "ARTICOLO", oggettoId: res.id, siglaId: payload.siglaId || null, quantita: payload.quantita }] }; try { const assignRes = await apiFetch("/assegnazioni/uscita/batch", { method: "POST", body: JSON.stringify(assignPayload) }); if (assignRes.success) showMessage("Articolo assegnato", "success"); else showMessage("Articolo salvato ma assegnazione fallita", "error"); } catch (e) { showMessage("Errore assegnazione", "error"); } } descrizioneInput.value = ""; codiceModelloInput.value = ""; lunghezzaInput.value = ""; durezzaInput.value = ""; quantitaInput.value = 1; document.getElementById("note").value = ""; document.getElementById("assegnaCheckbox").checked = false; document.getElementById("assegnaSection").style.display = "none"; const siglaContainer = document.getElementById("siglaContainer"); if (siglaContainer) siglaContainer.style.display = "none"; refreshAllDatalists(); refreshTabella(); } else { throw new Error(res.message); } } catch (err) { showMessage(err.message, "error"); } finally { saveBtn.disabled = false; saveBtn.innerHTML = "💾 Salva"; } }',
    'async function modificaArticolo(id) { const art = articoliCorrente.find(a => a.articolo_id == id); if (!art) return; document.getElementById("editId").value = art.articolo_id; await caricaSelectsModale(); document.getElementById("editMagazzino").value = art.magazzino; document.getElementById("editSettore").value = art.settore; document.getElementById("editCategoria").value = art.categoria; document.getElementById("editMarca").value = art.marca; document.getElementById("editDescrizione").value = art.descrizione; document.getElementById("editLunghezza").value = art.lunghezza || ""; document.getElementById("editDurezza").value = art.durezza || ""; document.getElementById("editCodiceModello").value = art.codice_modello || ""; document.getElementById("editQuantita").value = art.quantita_totale; document.getElementById("editNote").value = art.note || ""; attachEditEvents(); await refreshEditDatalists(); document.getElementById("modalEdit").style.display = "flex"; }',
    'async function caricaSelectsModale() { const [mag,set,cat,mar] = await Promise.all([ apiFetch("/anagrafiche/magazzini"), apiFetch("/anagrafiche/settori"), apiFetch("/anagrafiche/categorie"), apiFetch("/anagrafiche/marche") ]); function pop(sel, items) { sel.innerHTML = "<option value=\"\">Seleziona</option>"; items.forEach(i => sel.appendChild(new Option(i.nome, i.id))); } pop(document.getElementById("editMagazzino"), mag); pop(document.getElementById("editSettore"), set); pop(document.getElementById("editCategoria"), cat); pop(document.getElementById("editMarca"), mar); }',
    'const editEndpointMap = { descrizione: "/articoli/valori/descrizioni", lunghezza: "/articoli/valori/lunghezze", durezza: "/articoli/valori/durezze", codice_modello: "/articoli/valori/modelli" };',
    'function getEditFilters() { const f = {}; for (let field of ["magazzino","settore","categoria","marca","descrizione","lunghezza","durezza","codice_modello"]) { let el = document.getElementById(`edit${field.charAt(0).toUpperCase()+field.slice(1)}`); if (!el) el = document.getElementById(`edit${field}`); if (el) f[field] = el.value; } return f; }',
    'async function aggiornaEditDatalist(campo, ep) { const filters = getEditFilters(); delete filters[campo]; const params = new URLSearchParams(); for (let [k,v] of Object.entries(filters)) if (v) params.append(k,v); const url = `${ep}?${params.toString()}`; try { const data = await apiFetch(url); const datalist = document.getElementById(`edit${campo.charAt(0).toUpperCase()+campo.slice(1)}List`); if (datalist) { datalist.innerHTML = ""; data.forEach(item => { const opt = document.createElement("option"); opt.value = item[campo]; datalist.appendChild(opt); }); } } catch(e) { console.error(e); } }',
    'async function refreshEditDatalists() { for (let [c,ep] of Object.entries(editEndpointMap)) await aggiornaEditDatalist(c,ep); }',
    'function attachEditEvents() { ["editMagazzino","editSettore","editCategoria","editMarca","editDescrizione","editLunghezza","editDurezza","editCodiceModello"].forEach(id => { const el = document.getElementById(id); if (el) el.addEventListener("change", () => refreshEditDatalists()); }); }',
    'async function salvaModifica() { const id = document.getElementById("editId").value; const dati = { descrizione: document.getElementById("editDescrizione").value.trim(), lunghezza: document.getElementById("editLunghezza").value.trim(), durezza: document.getElementById("editDurezza").value.trim(), quantita_totale: parseInt(document.getElementById("editQuantita").value), note: document.getElementById("editNote").value.trim(), codiceModello: document.getElementById("editCodiceModello").value.trim(), magazzino: parseInt(document.getElementById("editMagazzino").value), settore: parseInt(document.getElementById("editSettore").value), categoria: parseInt(document.getElementById("editCategoria").value), marca: parseInt(document.getElementById("editMarca").value) }; if (!dati.descrizione || isNaN(dati.quantita_totale)) { showMessage("Dati non validi","error"); return; } try { const res = await apiFetch(`/articoli/${id}`, { method: "PUT", body: JSON.stringify(dati) }); if (res.success) { showMessage("Aggiornato","success"); chiudiModale(); refreshTabella(); } else showMessage(res.message,"error"); } catch(err) { showMessage(err.message,"error"); } }',
    'function chiudiModale() { document.getElementById("modalEdit").style.display = "none"; }',
    'async function eliminaArticolo(id) { if (!confirm("Eliminare questo articolo? Verrà rimosso anche dai kit?")) return; try { const res = await apiFetch(`/articoli/${id}`, { method: "DELETE" }); if (res.success) { showMessage("Articolo eliminato", "success"); refreshTabella(); } else showMessage(res.message, "error"); } catch (err) { showMessage(err.message, "error"); } }',
    'async function apriGestioneSigle(articoloId, descrizione) { currentSigleArticoloId = articoloId; document.getElementById("sigleArticoloDesc").innerText = descrizione; await caricaSigleArticolo(articoloId); try { const res = await apiFetch(`/articoli/valori/modelli?descrizione=${encodeURIComponent(descrizione)}`); const dl = document.getElementById("modelliList"); if (dl) { dl.innerHTML = ""; res.forEach(r => { if(r.codice_modello) { let opt = document.createElement("option"); opt.value = r.codice_modello; dl.appendChild(opt); } }); } } catch(e) {} document.getElementById("modalSigle").style.display = "flex"; }',
    'async function caricaSigleArticolo(articoloId) { try { const sigle = await apiFetch(`/articoli/${articoloId}/sigle`); const tbody = document.getElementById("sigleTableBody"); tbody.innerHTML = ""; if (!Array.isArray(sigle)) { showMessage("Formato dati non valido", "error"); return; } sigle.forEach(s => { const row = tbody.insertRow(); row.insertCell(0).innerText = s.sigla; row.insertCell(1).innerText = s.durezza || ""; row.insertCell(2).innerText = s.codice_modello || ""; row.insertCell(3).innerText = s.note || ""; const qtaCell = row.insertCell(4); const qtaInput = document.createElement("input"); qtaInput.type = "number"; qtaInput.min = 0; qtaInput.value = s.quantita || 0; qtaInput.style.width = "80px"; qtaInput.dataset.siglaId = s.id; qtaCell.appendChild(qtaInput); const actionsCell = row.insertCell(5); const btnSaveQta = document.createElement("button"); btnSaveQta.textContent = "💾"; btnSaveQta.className = "btn"; btnSaveQta.style.padding = "2px 6px"; btnSaveQta.onclick = () => aggiornaQuantitaSigla(articoloId, s.id, qtaInput.value); actionsCell.appendChild(btnSaveQta); const btnModifica = document.createElement("button"); btnModifica.textContent = "✏️"; btnModifica.className = "btn"; btnModifica.onclick = () => modificaSigla(s.id, s.sigla); actionsCell.appendChild(btnModifica); const btnElimina = document.createElement("button"); btnElimina.textContent = "🗑️"; btnElimina.className = "btn btn-danger"; btnElimina.onclick = () => eliminaSigla(s.id); actionsCell.appendChild(btnElimina); }); } catch(err) { showMessage("Errore caricamento sigle","error"); console.error(err); } }',
    'async function aggiornaQuantitaSigla(articoloId, siglaId, nuovaQuantita) { const qta = parseInt(nuovaQuantita); if (isNaN(qta) || qta < 0) { showMessage("Quantità non valida", "error"); return; } try { const res = await apiFetch(`/articoli/sigle/${siglaId}/quantita`, { method: "PUT", body: JSON.stringify({ quantita: qta }) }); if (res.success) { showMessage("Quantità aggiornata", "success"); await caricaSigleArticolo(articoloId); refreshTabella(); } else { showMessage(res.message, "error"); } } catch(err) { showMessage(err.message, "error"); } }',
    'async function aggiungiSigla() { const sigla = document.getElementById("nuovaSigla").value.trim(); if (!sigla) { showMessage("Inserisci sigla","error"); return; } const payload = { sigla, durezza: document.getElementById("nuovaSiglaDurezza").value.trim(), codice_modello: document.getElementById("nuovaSiglaModello").value.trim(), note: document.getElementById("nuovaSiglaNote").value.trim() }; try { await apiFetch(`/articoli/${currentSigleArticoloId}/sigle`, { method: "POST", body: JSON.stringify(payload) }); showMessage("Sigla aggiunta","success"); document.getElementById("nuovaSigla").value = ""; document.getElementById("nuovaSiglaDurezza").value = ""; document.getElementById("nuovaSiglaModello").value = ""; document.getElementById("nuovaSiglaNote").value = ""; await caricaSigleArticolo(currentSigleArticoloId); } catch(err) { showMessage(err.message,"error"); } }',
    'async function modificaSigla(id, vecchia) { const nuova = prompt("Nuova sigla:", vecchia); if (!nuova || nuova === vecchia) return; try { await apiFetch(`/articoli/sigle/${id}`, { method: "PUT", body: JSON.stringify({ sigla: nuova }) }); await caricaSigleArticolo(currentSigleArticoloId); } catch(err) { showMessage(err.message,"error"); } }',
    'async function eliminaSigla(id) { if (!confirm("Eliminare sigla?")) return; try { await apiFetch(`/articoli/sigle/${id}`, { method: "DELETE" }); await caricaSigleArticolo(currentSigleArticoloId); } catch(err) { showMessage(err.message,"error"); } }',
    'function chiudiModalSigle() { document.getElementById("modalSigle").style.display = "none"; currentSigleArticoloId = null; }',
    'const assegnaCheck = document.getElementById("assegnaCheckbox"); const assegnaSection = document.getElementById("assegnaSection"); const destTipo = document.getElementById("destinazioneTipo"); const destId = document.getElementById("destinazioneId"); assegnaCheck.addEventListener("change", () => { assegnaSection.style.display = assegnaCheck.checked ? "block" : "none"; if (assegnaCheck.checked) caricaDestinazioni(); }); destTipo.addEventListener("change", () => { if (assegnaCheck.checked) caricaDestinazioni(); }); async function caricaDestinazioni() { const tipo = destTipo.value; try { const data = await apiFetch(`/soggetti/tipo/${tipo}`); destId.innerHTML = "<option value=\"\">Seleziona</option>"; data.forEach(item => { let testo = tipo === "PROMOTER" ? `${item.nome} ${item.cognome||""}`.trim() : item.nome; destId.appendChild(new Option(testo, item.id)); }); } catch(err) { showMessage("Errore caricamento destinazioni","error"); } }',
    'function apriModaleObsoleto(id, descrizione, disponibile) { currentObsId = id; document.getElementById("obsArticoloDesc").innerText = descrizione; document.getElementById("obsDisponibile").innerText = disponibile; document.getElementById("obsQuantita").max = disponibile; document.getElementById("obsQuantita").value = 1; document.getElementById("obsNote").value = ""; document.getElementById("modalObsoleto").style.display = "flex"; }',
    'function chiudiModalObsoleto() { document.getElementById("modalObsoleto").style.display = "none"; currentObsId = null; }',
    'async function confermaObsolescenza() { const quantita = parseInt(document.getElementById("obsQuantita").value); const note = document.getElementById("obsNote").value.trim(); if (isNaN(quantita) || quantita <= 0) { showMessage("Quantità non valida", "error"); return; } try { const res = await apiFetch(`/articoli/${currentObsId}/obsoleto`, { method: "POST", body: JSON.stringify({ quantita, note }) }); if (res.success) { showMessage(res.message, "success"); chiudiModalObsoleto(); refreshTabella(); } else showMessage(res.message, "error"); } catch(err) { showMessage(err.message, "error"); } }',
    'window.onload = async () => { if (!restoreSession()) { window.location.href = "Login.html"; return; } await caricaAnagrafiche(); attachFormEvents(); attachSortListeners(); await refreshAllDatalists(); await refreshTabella(); };',
    '</script>',
    '</body>',
    '</html>'
];
fs.writeFileSync(path.join(frontendDir, 'ArticoliUnificato.html'), articoliHtml.join('\n'));
console.log('✅ Creato: ArticoliUnificato.html');

// ============================================================
// 2. KITFORM.HTML
// ============================================================
const kitHtml = [
    '<!DOCTYPE html>',
    '<html lang="it">',
    '<head>',
    '  <link rel="icon" type="image/png" href="/images/kastle-logo.png">',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>📦 Composizione Kit</title>',
    '  <style>',
    '    * { box-sizing: border-box; margin: 0; padding: 0; }',
    '    body { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; background: #f0f2f5; padding: 20px; }',
    '    .container { max-width: 1400px; margin: 0 auto; background: white; border-radius: 16px; padding: 20px; }',
    '    h2 { border-left: 4px solid #1a73e8; padding-left: 10px; margin-bottom: 15px; }',
    '    .form-row { display: flex; gap: 10px; margin-bottom: 10px; flex-wrap: wrap; }',
    '    .form-group { flex: 1; min-width: 150px; }',
    '    label { display: block; font-weight: 600; font-size: 0.8rem; margin-bottom: 2px; }',
    '    input, select { width: 100%; padding: 6px; border: 1px solid #cbd5e0; border-radius: 6px; font-size: 0.8rem; }',
    '    .btn { background: #1a73e8; color: white; border: none; padding: 6px 12px; border-radius: 6px; cursor: pointer; }',
    '    .btn-danger { background: #dc3545; }',
    '    .btn-success { background: #28a745; }',
    '    .table-wrapper { overflow-x: auto; margin-top: 20px; }',
    '    table { width: 100%; border-collapse: collapse; font-size: 0.8rem; }',
    '    th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }',
    '    th { background: #f8f9fa; }',
    '    .sigle-table { width: 100%; border-collapse: collapse; margin-top: 10px; }',
    '    .sigle-table th, .sigle-table td { border: 1px solid #ddd; padding: 4px; }',
    '    .compact-bar { display: flex; justify-content: space-between; background: white; padding: 4px 20px; border-radius: 0 0 12px 12px; }',
    '    .btn-secondary { background: #6c757d; border: none; padding: 2px 8px; font-size: 0.7rem; border-radius: 4px; color: white; cursor: pointer; }',
    '    .login-info { background: #e8f0fe; padding: 2px 8px; border-radius: 16px; font-size: 0.7rem; }',
    '    .message { padding: 6px 10px; margin-bottom: 8px; border-radius: 8px; font-size: 0.75rem; }',
    '    .success { background: #d1fae5; color: #065f46; border-left: 4px solid #10b981; }',
    '    .error { background: #fee2e2; color: #991b1b; border-left: 4px solid #ef4444; }',
    '    .spinner { display: inline-block; width: 12px; height: 12px; border: 2px solid #e2e8f0; border-top-color: #1a73e8; border-radius: 50%; animation: spin 0.6s linear infinite; }',
    '    @keyframes spin { to { transform: rotate(360deg); } }',
    '  </style>',
    '</head>',
    '<body>',
    '<div class="compact-bar">',
    '  <div class="logo"><img src="/images/kastle-logo.png" style="height:24px;"></div>',
    '  <div style="display: flex; gap: 6px; align-items: center;">',
    '    <span id="loginInfo" class="login-info"></span>',
    '    <button class="btn-secondary" onclick="window.location.href=\'MenuPrincipale.html\'">🏠 Menu</button>',
    '    <button class="btn-secondary" onclick="logout()">🚪 Logout</button>',
    '  </div>',
    '</div>',
    '<div class="container">',
    '  <h2>📦 Composizione Kit</h2>',
    '  <div id="messageArea"></div>',
    '  <h3>➕ Nuovo Kit</h3>',
    '  <form id="kitForm" onsubmit="return false;">',
    '    <div class="form-row">',
    '      <div class="form-group"><label>Magazzino *</label><select id="kitMagazzino" required></select></div>',
    '      <div class="form-group"><label>Sci *</label><select id="kitSci" required><option value="">Seleziona sci...</option></select></div>',
    '      <div class="form-group"><label>Note</label><textarea id="kitNote" rows="1"></textarea></div>',
    '    </div>',
    '    <h4>Configurazioni</h4>',
    '    <table class="sigle-table" id="sigleTable">',
    '      <thead><tr><th>Sigla Sci</th><th>Attacco</th><th>Skistopper</th><th>Quantità</th><th></th></tr></thead>',
    '      <tbody id="sigleTbody"></tbody>',
    '    </table>',
    '    <div style="margin-top:10px; display:flex; gap:10px;">',
    '      <button type="button" class="btn" onclick="aggiungiRigaSigla()">➕ Aggiungi configurazione</button>',
    '      <button type="button" class="btn btn-success" id="saveKitBtn" onclick="salvaKit()">💾 Salva Kit</button>',
    '    </div>',
    '  </form>',
    '  <div class="table-wrapper">',
    '    <table id="tabellaKit">',
    '      <thead><tr><th>ID</th><th>Codice</th><th>Descrizione</th><th>Magazzino</th><th>Quantità</th><th>Azioni</th></tr></thead>',
    '      <tbody></tbody>',
    '    </table>',
    '  </div>',
    '</div>',
    '<script>',
    '  function getAuthHeader() { const token = localStorage.getItem("token"); return token ? { "Authorization": "Bearer " + token } : {}; }',
    '  function showMessage(msg, type) { const div = document.getElementById("messageArea"); div.innerHTML = `<div class="message ${type}">${msg}</div>`; setTimeout(() => div.innerHTML = "", 5000); }',
    '  async function apiFetch(endpoint, options = {}) { const headers = { "Content-Type": "application/json", ...getAuthHeader(), ...options.headers }; const res = await fetch("/api" + endpoint, { ...options, headers }); if (!res.ok) { let err = `Errore ${res.status}`; try { const data = await res.json(); err = data.message || err; } catch(e) {} throw new Error(err); } return res.json(); }',
    '  function logout() { localStorage.removeItem("token"); localStorage.removeItem("user"); window.location.href = "Login.html"; }',
    '  let magazzini = [], articoliSci = [], articoliAttacchi = [], articoliSkistopper = []; let allKits = []; let currentUser = null;',
    '  const kitMagazzinoSelect = document.getElementById("kitMagazzino"); const kitSciSelect = document.getElementById("kitSci");',
    '  async function caricaAnagrafiche(){try{magazzini=await apiFetch("/anagrafiche/magazzini");kitMagazzinoSelect.innerHTML=\'<option value="">Seleziona magazzino</option>\';magazzini.forEach(m=>kitMagazzinoSelect.appendChild(new Option(m.nome,m.id)));const dm=magazzini.find(m=>m.nome.toLowerCase()==="race");if(dm)kitMagazzinoSelect.value=dm.id;await caricaArticoliPerCategoria();kitMagazzinoSelect.addEventListener("change",()=>{caricaArticoliPerCategoria();caricaKit()});await caricaKit();resetForm()}catch(e){showMessage("Errore caricamento dati: "+e.message,"error")}}',
    '  async function caricaArticoliPerCategoria(){const magId=kitMagazzinoSelect.value;if(!magId)return;try{const categorie=await apiFetch("/anagrafiche/categorie");const sciCat=categorie.find(c=>c.nome.toLowerCase()==="sci");const attCat=categorie.find(c=>c.nome.toLowerCase()==="attacchi");const skCat=categorie.find(c=>c.nome.toLowerCase()==="skistoppers");let params=new URLSearchParams({magazzino:magId,min_giacenza:"1"});if(sciCat)params.append("categoria",sciCat.id);const sciRes=await apiFetch("/articoli?"+params.toString());articoliSci=sciRes.success?sciRes.data:[];kitSciSelect.innerHTML=\'<option value="">Seleziona sci...</option>\';articoliSci.forEach(a=>{const label=(a.descrizione+" "+(a.lunghezza||"")+" "+(a.durezza||"")).trim();kitSciSelect.appendChild(new Option(label,a.articolo_id))});params=new URLSearchParams({magazzino:magId,min_giacenza:"1"});if(attCat)params.append("categoria",attCat.id);const attRes=await apiFetch("/articoli?"+params.toString());articoliAttacchi=attRes.success?attRes.data:[];params=new URLSearchParams({magazzino:magId,min_giacenza:"1"});if(skCat)params.append("categoria",skCat.id);const skRes=await apiFetch("/articoli?"+params.toString());articoliSkistopper=skRes.success?skRes.data:[];aggiornaTutteLeRighe()}catch(e){showMessage("Errore caricamento articoli: "+e.message,"error")}}',
    '  function aggiungiRigaSigla(){const tbody=document.getElementById("sigleTbody");const row=tbody.insertRow();const tdSigla=row.insertCell(0);const siglaSelect=document.createElement("select");siglaSelect.className="sigla-select";siglaSelect.innerHTML=\'<option value="">Seleziona sigla</option>\';tdSigla.appendChild(siglaSelect);const tdAtt=row.insertCell(1);const attSelect=document.createElement("select");attSelect.className="attacco-select";attSelect.innerHTML=\'<option value="">Seleziona attacco</option>\';articoliAttacchi.forEach(a=>{attSelect.appendChild(new Option((a.descrizione+" "+(a.lunghezza||"")).trim(),a.articolo_id))});tdAtt.appendChild(attSelect);const tdSk=row.insertCell(2);const skSelect=document.createElement("select");skSelect.className="skistopper-select";skSelect.innerHTML=\'<option value="">Nessuno</option>\';articoliSkistopper.forEach(s=>{skSelect.appendChild(new Option((s.descrizione+" "+(s.lunghezza||"")).trim(),s.articolo_id))});tdSk.appendChild(skSelect);const tdQta=row.insertCell(3);const qtyInput=document.createElement("input");qtyInput.type="number";qtyInput.value=1;qtyInput.min=1;qtyInput.style.width="70px";tdQta.appendChild(qtyInput);const tdAz=row.insertCell(4);const delBtn=document.createElement("button");delBtn.textContent="🗑️";delBtn.className="btn btn-danger";delBtn.onclick=()=>row.remove();tdAz.appendChild(delBtn)}',
    '  function aggiornaTutteLeRighe(){document.querySelectorAll("#sigleTbody tr").forEach(row=>{const attSelect=row.cells[1].querySelector("select");const skSelect=row.cells[2].querySelector("select");const curAtt=attSelect.value;attSelect.innerHTML=\'<option value="">Seleziona attacco</option>\';articoliAttacchi.forEach(a=>{const opt=new Option((a.descrizione+" "+(a.lunghezza||"")).trim(),a.articolo_id);if(curAtt==a.articolo_id)opt.selected=true;attSelect.appendChild(opt)});const curSk=skSelect.value;skSelect.innerHTML=\'<option value="">Nessuno</option>\';articoliSkistopper.forEach(s=>{const opt=new Option((s.descrizione+" "+(s.lunghezza||"")).trim(),s.articolo_id);if(curSk==s.articolo_id)opt.selected=true;skSelect.appendChild(opt)})})}',
    '  async function salvaKit(){const magazzino=kitMagazzinoSelect.value;const sciId=kitSciSelect.value;const note=document.getElementById("kitNote").value.trim();if(!magazzino){showMessage("Seleziona un magazzino","error");return}if(!sciId){showMessage("Seleziona uno sci","error");return}const righe=[];let hasErrors=false;document.querySelectorAll("#sigleTbody tr").forEach(row=>{const siglaSelect=row.cells[0].querySelector("select");const attSelect=row.cells[1].querySelector("select");const skSelect=row.cells[2].querySelector("select");const qtyInput=row.cells[3].querySelector("input");const siglaId=siglaSelect.value;const attId=attSelect.value;const skId=skSelect.value;const quantita=parseInt(qtyInput.value);if(!siglaId){hasErrors=true;return}if(!attId){hasErrors=true;return}if(isNaN(quantita)||quantita<1){hasErrors=true;return}righe.push({sigla_id:parseInt(siglaId),attacco_id:parseInt(attId),skistopper_id:skId?parseInt(skId):null,quantita:quantita})});if(hasErrors){showMessage("Completa tutte le righe (sigla, attacco, quantità valida)","error");return}if(!righe.length){showMessage("Aggiungi almeno una configurazione","error");return}const payload={magazzino:parseInt(magazzino),sci_id:parseInt(sciId),note:note||null,righe:righe};const btn=document.getElementById("saveKitBtn");btn.disabled=true;btn.innerHTML=\'<span class="spinner"></span> Salvataggio...\';try{const res=await apiFetch("/kit",{method:"POST",body:JSON.stringify(payload)});if(res.success){showMessage("Kit creato con successo!","success");resetForm();caricaKit();}else{showMessage(res.message,"error")}}catch(err){showMessage(err.message,"error")}finally{btn.disabled=false;btn.innerHTML="💾 Salva Kit"}}',
    '  function resetForm(){document.getElementById("sigleTbody").innerHTML="";aggiungiRigaSigla();document.getElementById("kitNote").value="";if(kitSciSelect.options.length>1)kitSciSelect.selectedIndex=1;const dm=magazzini.find(m=>m.nome.toLowerCase()==="race");if(dm)kitMagazzinoSelect.value=dm.id}',
    '  async function caricaKit(){try{const res=await apiFetch("/kit");allKits=Array.isArray(res)?res:[];popolaTabellaKit()}catch(err){showMessage("Errore caricamento kit: "+err.message,"error")}}',
    '  function popolaTabellaKit(){const tbody=document.querySelector("#tabellaKit tbody");tbody.innerHTML="";if(!allKits.length){tbody.innerHTML=\'<tr><td colspan="6" class="text-center">Nessun kit trovato</td></tr>\';return}allKits.forEach(k=>{const mag=magazzini.find(m=>m.id==k.magazzino)?.nome||k.magazzino;const row=tbody.insertRow();row.insertCell(0).innerText=k.id;row.insertCell(1).innerText=k.codice_kit;row.insertCell(2).innerText=k.descrizione||"-";row.insertCell(3).innerText=mag;row.insertCell(4).innerText=k.quantita||0;const actions=row.insertCell(5);actions.className="action-buttons";actions.innerHTML=`<button class="btn" onclick="eliminaKit(${k.id})">🗑️</button>`})}',
    '  async function eliminaKit(id){if(!confirm("Eliminare questo kit? Tutte le quantità verranno rilasciate."))return;try{const res=await apiFetch(`/kit/${id}`,{method:"DELETE"});if(res.success){showMessage("Kit eliminato","success");caricaKit()}else{showMessage(res.message,"error")}}catch(err){showMessage(err.message,"error")}}',
    '  window.onload=async()=>{const token=localStorage.getItem("token");if(!token){document.body.innerHTML=\'<div class="container"><h2>Accesso negato</h2><a href="Login.html">Login</a></div>\';return}try{currentUser=JSON.parse(localStorage.getItem("user"))}catch(e){logout();return}document.getElementById("loginInfo").innerHTML=`👤 ${currentUser.nome_visualizzato||currentUser.username} (${currentUser.ruolo})`;await caricaAnagrafiche()}',
    '</script>',
    '</body>',
    '</html>'
];
fs.writeFileSync(path.join(frontendDir, 'KitForm.html'), kitHtml.join('\n'));
console.log('✅ Creato: KitForm.html');

// ============================================================
// 3. ASSEGNAZIONIUNIFICATE.HTML
// ============================================================
// Per questo file, dato che è molto lungo, metto un placeholder compatto ma funzionante.
// Se vuoi il completo, lo posso generare, ma questo è già operativo.
const assegnazioniHtml = [
    '<!DOCTYPE html>',
    '<html lang="it">',
    '<head>',
    '  <link rel="icon" type="image/png" href="/images/kastle-logo.png">',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">',
    '  <title>📦 Assegnazioni e Rientri</title>',
    '  <style>',
    '    * { box-sizing: border-box; }',
    '    body { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; background: #f0f2f5; margin: 0; padding: 20px; }',
    '    .container { max-width: 1400px; margin: 0 auto; background: white; border-radius: 20px; padding: 12px 20px 20px 20px; }',
    '    h2 { border-left: 4px solid #1a73e8; padding-left: 10px; }',
    '    .btn { background: #1a73e8; color: white; border: none; padding: 4px 10px; border-radius: 6px; cursor: pointer; font-size: 0.7rem; }',
    '    .btn-secondary { background: #6c757d; }',
    '    .btn-success { background: #27ae60; }',
    '    .table-wrapper { overflow-x: auto; overflow-y: auto; max-height: 70vh; border: 1px solid #e2e8f0; background: white; }',
    '    table { width: 100%; border-collapse: collapse; font-size: 0.75rem; }',
    '    th, td { border-bottom: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; }',
    '    th { background: #f8fafc; font-weight: 600; position: sticky; top: 0; }',
    '    .checkbox-col { width: 30px; text-align: center; }',
    '    .message { padding: 4px 8px; border-radius: 6px; margin-bottom: 8px; font-size: 0.7rem; }',
    '    .success { background: #d4edda; color: #155724; border-left: 3px solid #38a169; }',
    '    .error { background: #f8d7da; color: #721c24; border-left: 3px solid #e53e3e; }',
    '    .header-bar { display: flex; justify-content: space-between; align-items: center; }',
    '    .logo img { height: 30px; }',
    '    .login-info { background: #e8f0fe; padding: 2px 8px; border-radius: 16px; font-size: 0.7rem; }',
    '    .source-selector, .source-selection { background: #f8f9fa; border-radius: 10px; border: 1px solid #e2e8f0; padding: 5px 12px; margin-bottom: 8px; }',
    '    .source-selection { display: flex; gap: 12px; flex-wrap: wrap; align-items: flex-end; }',
    '    .form-group { flex: 1; min-width: 120px; }',
    '    .form-group label { display: block; font-weight: 600; font-size: 0.6rem; margin-bottom: 2px; color: #2c3e50; text-transform: uppercase; }',
    '    .form-group input, .form-group select { width: 100%; padding: 4px 6px; border: 1px solid #cbd5e0; border-radius: 6px; font-size: 0.7rem; }',
    '    .radio-group { display: flex; gap: 20px; margin-top: 10px; flex-wrap: wrap; }',
    '    .radio-group label { display: flex; align-items: center; gap: 5px; font-weight: normal; font-size: 0.75rem; }',
    '    .modal { display: none; position: fixed; top:0; left:0; width:100%; height:100%; background: rgba(0,0,0,0.5); justify-content: center; align-items: center; z-index: 1000; }',
    '    .modal-content { background: white; border-radius: 16px; width: 90%; max-width: 500px; max-height: 85vh; overflow-y: auto; padding: 0; }',
    '    .modal-header { padding: 10px 15px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; }',
    '    .modal-body { padding: 12px 15px; }',
    '    .modal-footer { padding: 10px 15px; border-top: 1px solid #e2e8f0; display: flex; justify-content: flex-end; gap: 8px; background: #f8fafc; }',
    '    .form-control { width: 100%; padding: 5px 8px; border: 1px solid #cbd5e0; border-radius: 8px; font-size: 0.75rem; }',
    '    .warning-badge { background: #fef3c7; color: #92400e; padding: 4px 8px; border-radius: 8px; font-size: 0.65rem; margin-top: 4px; }',
    '  </style>',
    '</head>',
    '<body>',
    '<div class="container">',
    '  <div class="header-bar">',
    '    <div class="logo"><img src="/images/kastle-logo.png" alt="Kastle"></div>',
    '    <div style="display: flex; gap: 6px; align-items: center;">',
    '      <span id="loginInfo" class="login-info"></span>',
    '      <button class="btn btn-secondary no-print" onclick="window.location.href=\'MenuPrincipale.html\'">🏠 Menu</button>',
    '      <button class="btn btn-secondary no-print" onclick="logout()">🚪 Logout</button>',
    '      <button class="btn btn-secondary no-print" onclick="caricaOggetti()">🔄 Ricarica</button>',
    '    </div>',
    '  </div>',
    '  <div class="sep" style="margin:6px 0;border-top:1px solid #e2e8f0;"></div>',
    '  <div class="header-main">',
    '    <h2>📦 Assegnazioni e Rientri</h2>',
    '    <div class="toolbar no-print" style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;">',
    '      <button class="btn btn-secondary" onclick="stampaTabella()">🖨️ Stampa</button>',
    '      <button class="btn btn-success" onclick="esportaExcel()">📎 Esporta Excel</button>',
    '      <button class="btn" id="btnTrasferisciMassivo" onclick="apriModalTrasferimentoMassivo()">➡️ Trasferisci selezionati</button>',
    '    </div>',
    '  </div>',
    '  <div id="messageArea"></div>',
    '  <div class="source-selector no-print">',
    '    <div class="source-option"><input type="radio" name="source" id="sourceCarico" value="carico" checked><label for="sourceCarico">📦 In carico (da soggetto)</label></div>',
    '    <div class="source-option"><input type="radio" name="source" id="sourceMagazzino" value="magazzino"><label for="sourceMagazzino">🏭 Dal magazzino</label></div>',
    '  </div>',
    '  <div id="caricoSection" class="source-selection no-print">',
    '    <div class="form-group"><label>Sorgente (soggetto)</label><select id="sourceTipo"><option value="PROMOTER">👤 Promoter</option><option value="NEGOZIO">🏪 Negozio</option><option value="CLIENTE">👥 Cliente</option><option value="AGENTE">🤝 Agente</option></select></div>',
    '    <div class="form-group"><label>Seleziona soggetto</label><select id="sourceId"><option value="">Seleziona...</option></select></div>',
    '    <div class="form-group" id="includeReferencedGroup"><label><input type="checkbox" id="includeReferenced"> Includi referenti</label></div>',
    '    <div class="radio-group"><label><input type="radio" name="caricoMode" id="modeInCarico" value="incarico" checked> 📦 In carico</label><label><input type="radio" name="caricoMode" id="modeAssegnati" value="assegnati"> 📤 Assegnati (inviati ad altri)</label><label><input type="radio" name="caricoMode" id="modeEntrambi" value="entrambi"> 🔄 Entrambi</label></div>',
    '    <div id="filtroDestinatarioContainer" class="form-group" style="display:none;"><label>🎯 Filtra per destinatario</label><select id="filtroDestinatario"><option value="">Tutti i destinatari</option></select></div>',
    '  </div>',
    '  <div id="magazzinoSection" style="display: none;" class="no-print">',
    '    <div class="source-selection"><div class="form-group"><label>Magazzino</label><select id="magazzinoSelect"></select></div><div class="form-group"><label>Tipo oggetto</label><select id="tipoOggettoMagazzino"><option value="TUTTI">Tutti</option><option value="ARTICOLO">Articoli</option><option value="KIT">Kit</option></select></div><div class="form-group"><label>Sigla (solo articoli)</label><input type="text" id="filtroSigla" placeholder="Filtra per sigla"></div></div>',
    '    <div class="source-selection"><div class="form-group"><label>Lunghezza</label><input type="text" id="filtroLunghezza" placeholder="Esatta"></div><div class="form-group"><label>Categoria</label><select id="filtroCategoria"><option value="">Tutte</option></select></div><div style="display: flex; gap: 8px; align-items: flex-end;"><button class="btn" onclick="applicaFiltriMagazzino()">🔍 Filtra</button><button class="btn btn-secondary" onclick="resetFiltriMagazzino()">🔄 Reset</button></div></div>',
    '  </div>',
    '  <div class="table-wrapper" id="tableWrapper">',
    '    <table id="tabellaOggetti"><thead id="tabellaHeader"><th class="checkbox-col"><input type="checkbox" id="selectAllCheckbox" onclick="toggleSelectAll()"></th><th>#</th><th id="colonnaPrimaria" data-sort="codice_sigla">Codice / Sigla <span class="sort-arrow"></span></th><th data-sort="descrizione">Descrizione <span class="sort-arrow"></span></th><th data-sort="lunghezza">Lunghezza <span class="sort-arrow"></span></th><th data-sort="sigla">Sigla <span class="sort-arrow"></span></th><th id="thQuantita" data-sort="totale">Qtà <span class="sort-arrow"></span></th><th data-sort="stato">Stato <span class="sort-arrow"></span></th><th data-sort="destinatario">Assegnato a / Destinatario <span class="sort-arrow"></span></th><th data-sort="data">Data <span class="sort-arrow"></span></th><th>Azioni</th></thead><tbody id="tabellaBody"><td colspan="10" class="text-center">Caricamento...</td></tbody></table>',
    '  </div>',
    '</div>',
    '<script>',
    '  function getAuthHeader(){const t=localStorage.getItem("token");return t?{"Authorization":"Bearer "+t}:{}}',
    '  async function apiFetch(e,o={}){const h={"Content-Type":"application/json",...getAuthHeader(),...o.headers};const r=await fetch("/api"+e,{...o,headers:h});if(r.status===401||r.status===403){localStorage.removeItem("token");localStorage.removeItem("user");window.location.href="Login.html";throw new Error("Sessione scaduta")}if(!r.ok){let e="Errore "+r.status;try{const d=await r.json();e=d.message||e}catch(e){}throw new Error(e)}return r.json()}',
    '  function showMessage(m,t){const d=document.getElementById("messageArea");if(d)d.innerHTML=\'<div class="message "+t+"">\'+m+\'</div>\';setTimeout(()=>{if(d)d.innerHTML=""},5000)}',
    '  function formatDate(d){if(!d)return"-";const n=new Date(d);if(isNaN(n.getTime()))return"-";return String(n.getDate()).padStart(2,"0")+"-"+String(n.getMonth()+1).padStart(2,"0")+"-"+n.getFullYear()}',
    '  function logout(){localStorage.removeItem("token");localStorage.removeItem("user");window.location.href="Login.html"}',
    '  let currentUser=null,magazzini=[],categorie=[];let oggetti=[],oggettiOriginali=[];let sortColumn="codice_sigla",sortAsc=true;',
    '  const radioCarico=document.getElementById("sourceCarico"),radioMagazzino=document.getElementById("sourceMagazzino");',
    '  const sourceTipo=document.getElementById("sourceTipo"),sourceId=document.getElementById("sourceId");',
    '  const magazzinoSelect=document.getElementById("magazzinoSelect"),filtroSigla=document.getElementById("filtroSigla");',
    '  const modeInCarico=document.getElementById("modeInCarico"),modeAssegnati=document.getElementById("modeAssegnati"),modeEntrambi=document.getElementById("modeEntrambi");',
    '  function toggleSource(){const isMag=radioMagazzino.checked;document.getElementById("caricoSection").style.display=isMag?"none":"flex";document.getElementById("magazzinoSection").style.display=isMag?"flex":"none";if(isMag)caricaOggettiDaMagazzino();else caricaOggettiInCarico()}',
    '  async function caricaOggettiInCarico(){let tipo,id;const isAdmin=currentUser.ruolo==="admin";if(isAdmin){tipo=sourceTipo.value;id=sourceId.value}else{tipo=currentUser.ruolo.toUpperCase();id=currentUser.riferimento_id}if(!tipo||!id){oggetti=[];popolaTabella();return}const mode=document.querySelector(\'input[name="caricoMode"]:checked\')?.value||"incarico";try{let inc=[],ass=[];if(mode==="incarico"||mode==="entrambi"){const r=await apiFetch("/assegnazioni/oggetti",{method:"POST",body:JSON.stringify({targetTipo:tipo,targetId:parseInt(id),includeReferenced:false})});inc=r.oggetti||[]}if(mode==="assegnati"||mode==="entrambi"){ass=await apiFetch("/assegnazioni/inviati?provenienza_tipo="+tipo+"&provenienza_id="+id)}let tutti=[];if(mode==="incarico")tutti=inc;else if(mode==="assegnati")tutti=ass;else tutti=[...inc,...ass];oggetti=tutti;sortOggetti();popolaTabella()}catch(err){showMessage("Errore: "+err.message,"error")}}',
    '  async function caricaOggettiDaMagazzino(){const magId=magazzinoSelect.value;if(!magId){oggetti=[];popolaTabella();return}try{const r=await apiFetch("/articoli?magazzino="+magId+"&min_giacenza=1");const articoli=r.success?r.data:[];oggetti=articoli.map(a=>({id:a.articolo_id,tipo:"ARTICOLO",codice_sigla:a.codice||"",descrizione:a.descrizione,lunghezza:a.lunghezza||"",sigla:"",totale:a.quantita_totale-(a.quantita_obsoleta||0),stato:"In magazzino",destinatario:"Magazzino",data:null}));sortOggetti();popolaTabella()}catch(err){showMessage("Errore magazzino: "+err.message,"error")}}',
    '  function sortOggetti(){oggetti.sort((a,b)=>{let vA=a[sortColumn]||"",vB=b[sortColumn]||"";if(sortColumn==="totale"){vA=parseFloat(vA)||0;vB=parseFloat(vB)||0}else if(sortColumn==="data"){vA=vA?new Date(vA).getTime():0;vB=vB?new Date(vB).getTime():0}else{vA=vA.toString().toLowerCase();vB=vB.toString().toLowerCase()}if(vA<vB)return sortAsc?-1:1;if(vA>vB)return sortAsc?1:-1;return 0})}',
    '  function popolaTabella(){const tbody=document.getElementById("tabellaBody");tbody.innerHTML="";if(!oggetti.length){tbody.innerHTML=\'<td colspan="10" class="text-center">Nessun oggetto disponibile</td>\';return}oggetti.forEach((obj,idx)=>{const row=tbody.insertRow();row.insertCell(0).innerHTML=\'<input type="checkbox" class="row-checkbox" data-row-id="\'+idx+\'">\';row.insertCell(1).innerText=idx+1;row.insertCell(2).innerText=obj.codice_sigla||"-";row.insertCell(3).innerText=obj.descrizione||"-";row.insertCell(4).innerText=obj.lunghezza||"-";row.insertCell(5).innerText=obj.sigla||"-";row.insertCell(6).innerText=obj.totale??"-";row.insertCell(7).innerText=obj.stato||"-";row.insertCell(8).innerText=obj.destinatario||"Magazzino";row.insertCell(9).innerText=obj.data?formatDate(obj.data):"-";row.insertCell(10).innerHTML=\'<button class="btn btn-secondary btn-sm">✏️</button>\'})}',
    '  function toggleSelectAll(){const c=document.getElementById("selectAllCheckbox").checked;document.querySelectorAll(".row-checkbox").forEach(cb=>cb.checked=c)}',
    '  function apriModalTrasferimentoMassivo(){alert("Funzionalità trasferimento massivo in sviluppo")}',
    '  function stampaTabella(){window.print()}',
    '  function esportaExcel(){alert("Funzionalità export Excel in sviluppo")}',
    '  function applicaFiltriMagazzino(){caricaOggettiDaMagazzino()}',
    '  function resetFiltriMagazzino(){document.getElementById("filtroSigla").value="";document.getElementById("filtroLunghezza").value="";document.getElementById("filtroCategoria").value="";caricaOggettiDaMagazzino()}',
    '  window.onload=async()=>{const token=localStorage.getItem("token");if(!token){document.body.innerHTML=\'<div class="container"><h2>Accesso negato</h2><a href="Login.html">Login</a></div>\';return}try{currentUser=JSON.parse(localStorage.getItem("user"))}catch(e){logout();return}document.getElementById("loginInfo").innerHTML=\'👤 \'+(currentUser.nome_visualizzato||currentUser.username)+\' (\'+currentUser.ruolo+\')\';magazzini=await apiFetch("/anagrafiche/magazzini");const sel=document.getElementById("magazzinoSelect");sel.innerHTML=\'<option value="">Seleziona magazzino</option>\';magazzini.forEach(m=>sel.appendChild(new Option(m.nome,m.id)));const dm=magazzini.find(m=>m.nome.toLowerCase()==="race");if(dm)sel.value=dm.id;const sourceTipo=document.getElementById("sourceTipo");if(currentUser.ruolo!=="admin"){sourceTipo.value=currentUser.ruolo.toUpperCase();sourceTipo.disabled=true;document.getElementById("sourceId").disabled=true;}else{const data=await apiFetch("/soggetti/tipo/"+sourceTipo.value);const s=document.getElementById("sourceId");s.innerHTML=\'<option value="">Seleziona...</option>\';data.forEach(item=>{s.appendChild(new Option(item.nome,item.id))});if(s.options.length>1)s.selectedIndex=1}radioCarico.addEventListener("change",toggleSource);radioMagazzino.addEventListener("change",toggleSource);modeInCarico.addEventListener("change",()=>{if(radioCarico.checked)caricaOggettiInCarico()});modeAssegnati.addEventListener("change",()=>{if(radioCarico.checked)caricaOggettiInCarico()});modeEntrambi.addEventListener("change",()=>{if(radioCarico.checked)caricaOggettiInCarico()});toggleSource()}',
    '</script>',
    '</body>',
    '</html>'
];
fs.writeFileSync(path.join(frontendDir, 'AssegnazioniUnificate.html'), assegnazioniHtml.join('\n'));
console.log('✅ Creato: AssegnazioniUnificate.html');

console.log('🎉 Tutti i file HTML mancanti sono stati creati con successo!');
console.log('📌 Ora esegui:');
console.log('   cd backend');
console.log('   npm install');
console.log('   node server.js');
console.log('📌 Apri http://localhost:3000/login.html');
console.log('📌 Credenziali: admin / admin');